"""Deterministic offline engine.

Not a toy: this backend is how the whole workflow — gates, state transitions,
validation, git, resume — is exercised in CI without a model, a network or an
API key. It produces schema-valid output derived from the request metadata, and
in EDIT mode it makes a real (small, contained) file change so the validation
and delivery stages have something genuine to work with.
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import Any

from orchestrator.core.logging import get_logger
from orchestrator.engine.base import Engine, EngineMode, EngineRequest, EngineResponse

logger = get_logger("engine.mock")

DEFAULT_MOCK_FILE = "ORCHESTRATOR_MOCK_CHANGES.md"


class MockEngine(Engine):
    name = "mock"
    supports_editing = True

    def __init__(self, *, edit_file: str = DEFAULT_MOCK_FILE, fail_task: str | None = None) -> None:
        self.edit_file = edit_file
        #: Force a task to fail — used by tests covering the remediation loop.
        self.fail_task = fail_task
        self.calls: list[EngineRequest] = []

    def available(self) -> tuple[bool, str]:
        return True, "offline deterministic engine"

    def complete(self, request: EngineRequest) -> EngineResponse:
        self.calls.append(request)
        started = time.monotonic()

        if self.fail_task and request.task == self.fail_task:
            from orchestrator.core.errors import EngineError

            raise EngineError(f"MockEngine was configured to fail on task '{request.task}'.")

        handler = {
            "requirements": self._requirements,
            "plan": self._plan,
            "implement": self._implement,
            "review": self._review,
        }.get(request.task, self._generic)

        payload = handler(request)
        return EngineResponse(
            text="",
            structured=payload,
            raw={"mock": True, "task": request.task},
            duration_seconds=time.monotonic() - started,
        )

    # -- handlers ---------------------------------------------------------------- #

    @staticmethod
    def _meta(request: EngineRequest) -> dict[str, Any]:
        return request.metadata or {}

    def _requirements(self, request: EngineRequest) -> dict[str, Any]:
        meta = self._meta(request)
        issue = meta.get("issue", {})
        criteria: list[str] = issue.get("acceptance_criteria") or []
        if not criteria:
            criteria = [f"The behaviour described in {issue.get('key', 'the ticket')} is implemented."]
        requirements = [
            {
                "id": f"R{index}",
                "title": criterion[:70],
                "statement": criterion,
                "acceptance_criteria": [criterion],
                "priority": "must",
                "source": "ticket",
            }
            for index, criterion in enumerate(criteria, start=1)
        ]
        return {
            "issue_key": issue.get("key", meta.get("issue_key", "UNKNOWN")),
            "platform": meta.get("platform", "generic"),
            "summary": issue.get("summary", "Requirements derived offline by the mock engine."),
            "requirements": requirements,
            "non_goals": ["Anything not stated on the ticket."],
            "assumptions": ["Existing architecture and conventions are followed."],
            "open_questions": [],
        }

    def _plan(self, request: EngineRequest) -> dict[str, Any]:
        meta = self._meta(request)
        requirements = (meta.get("requirements") or {}).get("requirements", [])
        steps = [
            {
                "id": f"S{index}",
                "title": f"Implement {req.get('title', 'requirement')}",
                "intent": req.get("statement", ""),
                "target_files": [self.edit_file],
                "satisfies": [req.get("id", f"R{index}")],
                "depends_on": [f"S{index - 1}"] if index > 1 else [],
                "verification": "Project build and lint pass.",
                "risk": "low",
            }
            for index, req in enumerate(requirements, start=1)
        ] or [
            {
                "id": "S1",
                "title": "Apply the described change",
                "intent": "Single-step fallback plan.",
                "target_files": [self.edit_file],
                "satisfies": [],
                "depends_on": [],
                "verification": "Project build and lint pass.",
                "risk": "low",
            }
        ]
        return {
            "issue_key": meta.get("issue_key", "UNKNOWN"),
            "platform": meta.get("platform", "generic"),
            "summary": "Offline plan generated by the mock engine.",
            "steps": steps,
            "test_strategy": ["Run the platform's unit test target."],
            "rollback": "Revert the branch; no migrations or remote state involved.",
            "risks": ["Mock engine output is illustrative, not real code."],
            "out_of_scope": [],
        }

    def _implement(self, request: EngineRequest) -> dict[str, Any]:
        meta = self._meta(request)
        plan = meta.get("plan") or {}
        steps = plan.get("steps", [])
        changed: list[dict[str, Any]] = []

        if request.mode is EngineMode.EDIT and request.cwd:
            target = Path(request.cwd) / self.edit_file
            existed = target.exists()
            lines = [
                f"# Orchestrator run — {meta.get('issue_key', 'UNKNOWN')}",
                "",
                "This file was produced by the offline mock engine so that the",
                "validation and delivery stages have a real change to operate on.",
                "",
            ]
            lines += [f"- {step.get('id')}: {step.get('title')}" for step in steps]
            target.write_text("\n".join(lines) + "\n", encoding="utf-8")
            changed.append(
                {
                    "path": self.edit_file,
                    "change_type": "modified" if existed else "added",
                    "lines_added": len(lines),
                    "lines_removed": 0,
                }
            )

        return {
            "issue_key": meta.get("issue_key", "UNKNOWN"),
            "completed_step_ids": [s.get("id") for s in steps],
            "skipped_step_ids": [],
            "file_changes": changed,
            "notes": ["Generated by MockEngine — no real code was written."],
        }

    def _review(self, request: EngineRequest) -> dict[str, Any]:
        meta = self._meta(request)
        issue_key = meta.get("issue_key", "UNKNOWN")
        summary = meta.get("issue", {}).get("summary", "change")
        requirements = (meta.get("requirements") or {}).get("requirements", [])
        return {
            "issue_key": issue_key,
            "headline": f"{issue_key}: {summary}",
            "what_changed": [f"Touched {path}" for path in meta.get("touched_paths", [])]
            or ["No files reported as changed."],
            "risk_notes": ["Produced by the mock engine; review manually before merging."],
            "reviewer_checklist": [
                "Confirm the change matches the ticket's acceptance criteria",
                "Confirm tests cover the new behaviour",
            ],
            "requirements_coverage": {r.get("id", "R?"): "covered" for r in requirements},
            "commit_message": f"chore({issue_key.split('-')[0].lower()}): {summary}\n\nRefs: {issue_key}",
            "pr_title": f"{issue_key}: {summary}",
            "pr_body": (
                f"## Summary\n\n{summary}\n\n"
                f"## Ticket\n\n{issue_key}\n\n"
                "## Validation\n\nSee the orchestrator validation report attached to the run.\n"
            ),
        }

    def _generic(self, request: EngineRequest) -> dict[str, Any]:
        return {"task": request.task, "note": "MockEngine has no handler for this task."}
