"""iOS specialist."""

from __future__ import annotations

import platform as _platform

from orchestrator.agents.base import AgentContext
from orchestrator.agents.platform.base import PlatformAgent, PreflightReport
from orchestrator.core.models import Platform
from orchestrator.core.process import which


class IOSPlatformAgent(PlatformAgent):
    name = "platform-ios"
    responsibility = "Contribute iOS/Swift conventions and pre-flight checks."
    platform = Platform.IOS
    skill_tags = ("ios",)

    def preflight(self, ctx: AgentContext) -> PreflightReport:
        report = PreflightReport(platform=Platform.IOS)
        profile = ctx.profile.ios
        root = ctx.repo_path

        if profile is None:
            report.blockers.append("Repository was classified as iOS but has no iOS profile.")
            return report

        if not profile.primary_container and not profile.swift_package:
            report.blockers.append(
                "No .xcodeproj, .xcworkspace or Package.swift found — nothing to build."
            )

        if _platform.system() != "Darwin":
            report.warnings.append(
                "Not running on macOS: xcodebuild checks will be skipped, so a build "
                "regression will not be caught by this run."
            )
        elif not which("xcodebuild"):
            report.warnings.append("xcodebuild not on PATH; install Xcode command line tools.")

        if profile.has_swiftlint and not which("swiftlint"):
            report.warnings.append(
                "The repository configures SwiftLint but swiftlint is not installed; "
                "lint will be skipped."
            )

        if profile.uses_cocoapods and not (root / "Pods").exists():
            report.warnings.append("Podfile present but Pods/ is missing — run `pod install` first.")

        if profile.uses_tuist:
            report.warnings.append(
                "Tuist project: generated Xcode files must not be edited directly; "
                "edit the manifests instead."
            )

        report.facts = {
            "container": profile.primary_container or "(swift package)",
            "schemes": ", ".join(profile.schemes[:5]) or "(none discovered)",
            "swiftlint": "yes" if profile.has_swiftlint else "no",
            "min_ios": profile.min_ios_version or "unknown",
        }
        return report

    def guidance(self, ctx: AgentContext) -> str:
        profile = ctx.profile.ios
        if profile is None:
            return ""
        lines = ["Platform specifics for this repository:"]
        if profile.uses_tuist:
            lines.append("- Project files are generated by Tuist; edit `Project.swift`, not the .pbxproj.")
        elif profile.xcodeproj:
            lines.append(
                "- Adding a new file requires it to be added to the Xcode target; prefer "
                "extending existing files when the plan allows."
            )
        if profile.swift_package:
            lines.append("- This is (also) a Swift package; keep `Package.swift` targets consistent.")
        if profile.has_swiftlint:
            lines.append("- SwiftLint runs in strict mode; new warnings will fail validation.")
        return "\n".join(lines) if len(lines) > 1 else ""
